[package]
name = "rapture-assist/Raptured-Fluent"
version = "1.8"
license = "Apache-2.0"
authors = ["stxdev"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "lucasmzreal/fastsignal@10.3.2"
Ripple = "littensy/ripple@0.9.1"
Flipper = "reselim/flipper@2.0.0"
